openapi: 3.0.3
info:
  title: TOURNAMENT MANAGEMENT SYSTEM
  contact:
    email: xab.is@yandex.ru
  version: 1.0.0
tags:
  - name: authentication
    description: Login and register
  - name: tournament
    description: Tournament management
  - name: invitation
    description: Invitations to tournament
paths:
#  TODO 27.08 написать про token_location
  /auth/register:
    post:
      tags:
        - authentication
      summary: Register new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        200:
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /auth/login:
    post:
      tags:
        - authentication
      summary: Login to account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /tournamen/my_tournaments:
    get:
      tags:
        - tournament
      summary: Get information about current user's tournaments
      responses:
        200:
          description: Information current user's tournaments successfully sent
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TournamentDto'
  /tournament:
    post:
      tags:
        - tournament
      summary: Create new tournament
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TournamentCreationRequest'
      responses:
        201:
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TournamentDto'
  /tournament/{tournamentId}:
    get:
      tags:
        - tournament
      summary: Get information about specific tournament
      parameters:
        - name: tournamentId
          in: path
          required: true
          description: Id of tournament
          schema:
            type: integer
            example: 10
      responses:
        200:
          description: Information about specific tournament successfully sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TournamentDto'
  /tournament/{tournamentId}/register:
    put:
      tags:
        - tournament
      summary: Register current user to specific tournament
      parameters:
        - name: tournamentId
          in: path
          required: true
          description: Id of tournament
          schema:
            type: integer
            example: 10
      responses:
        200:
          description: Current user successfully registered to tournament
  /tournament/{tournamentId}/start:
    put:
      tags:
        - tournament
      summary: Distributes participants into groups and generates matches for the first stage of the tournament
      parameters:
        - name: tournamentId
          in: path
          required: true
          description: Id of tournament
          schema:
            type: integer
            example: 10
      responses:
        200:
          description: Started tournament
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TournamentDto'
  /invitation:
    post:
      tags:
        - invitation
      summary: Send invitation to tournament
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteRequest'
      responses:
        200:
          description: User successfully invited
  /invitation/{invitationId}/accept:
    put:
      tags:
        - invitation
      summary: Accept invitation
      parameters:
        - name: invitationId
          in: path
          required: true
          description: id of invitation
          schema:
            type: integer
      responses:
        200:
          description: Invitation successfully accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TournamentDto'
components:
  schemas:
    UserDto:
      type: object
      properties:
        userId:
          type: integer
          example: 10
        username:
          type: string
          example: 'ivanov'
        firstname:
          type: string
          example: 'Ivan'
        lastname:
          type: string
          example: 'Ivanov'
        email:
          type: string
          example: 'ivan@example.com'
    GroupDto:
      # TODO 14.08 дописать
      type: object
    StageDto:
      type: object
      properties:
        stageId:
          type: integer
          example: 10
        stageType:
          type: string
          example: 'SINGLE_ELIMINATION'
          enum:
            - SINGLE_ELIMINATION
            - PLAY_OFFS
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupDto'
        orderNumber:
          type: integer
          example: 1
    TournamentDto:
      type: object
      properties:
        tournamentId:
          type: integer
          example: 10
        name:
          type: string
          example: 'Tennis'
        description:
          type: string
          example: 'Tournament between colleagues'
        startDate:
          type: string
          format: 'yyyy-MM-dd'
          example: '2024-01-01'
        creator:
          $ref: '#/components/schemas/UserDto'
        participants:
          type: array
          items:
            $ref: '#/components/schemas/UserDto'
        tournamentStatus:
          type: string
          example: 'NOT_STARTED'
          enum:
            - NOT_STARTED
            - STARTED
            - FINISHED
            - CANCELED
        stages:
          type: array
          items:
            $ref: '#/components/schemas/StageDto'
    TournamentCreationRequest:
      type: object
      properties:
        name:
          type: string
          example: 'Tennis'
        description:
          type: string
          example: 'Tournament between colleagues'
        startDate:
          type: string
          format: 'yyyy-MM-dd'
          example: '2024-01-01'
        type:
          type: string
          example: 'SINGLE_ELIMINATION'
          enum:
            - ROUND_ROBIN
            - SINGLE_ELIMINATION
            - PLAY_OFFS
    InviteRequest:
      type: object
      properties:
        tournamentId:
          type: integer
          example: 10
        username:
          type: string
          example: 'ivanov'
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
          example: 'ivanov'
        firstname:
          type: string
          example: 'Ivan'
        lastname:
          type: string
          example: 'Ivanov'
        email:
          type: string
          example: 'ivan@example.com'
        password:
          type: string
          example: '***'
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          example: 'ivanov'
        password:
          type: string
          example: '***'
